# the goal is to create a metric to evaluate the date found by our models

In [33]:
import pandas as pd
from ephesus.date import get_data_json, get_dates, get_data_targets_json, get_dates_targets

In [2]:
# get feature sample
sample_size = 30
df_X = get_data_json()
df_X_sample = get_dates(df_X.sample(sample_size).copy())
# get target dates
df_y = get_dates_targets(get_data_targets_json())

In [6]:
df_X_sample["fichier"].head().to_list()

['2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-526e-4736-8e5b-bc95ae00f890_translation.json',
 'a5050600-95ef-43d8-a5fa-a57c791bf843_6bdcc550-786f-466f-adf8-b3788f458e11_translation.json',
 'a5050600-95ef-43d8-a5fa-a57c791bf843_0b17a3f7-07fd-420f-a7e9-c6ac3a91f0d8_translation.json',
 'a5050600-95ef-43d8-a5fa-a57c791bf843_6e530b73-6a24-47b2-956c-ea6cae802254_translation.json',
 'c619f0e1-7c22-4047-adb2-df4dec6643ba_3694c83a-bd98-a9b0-b01a-f5e6ee3de1ac_translation.json']

In [7]:
df_y["fichier"].head().to_list()

['2d035c4b-cdfa-4982-87dc-916fe07a0824_249f1d30-1a50-42de-a3a6-20c295f770c7_extraction.json',
 '2d035c4b-cdfa-4982-87dc-916fe07a0824_019a0add-5b4a-4cb9-b999-daeb5e2a54fd_extraction.json',
 '55d674cc-3389-4cf6-ab7c-1f1b9fa1b6ed_02a55241-ccf4-4f9a-87ac-23e0ac71e576_extraction.json',
 '9f980dcf-b431-4e67-876f-2b8e288b7900_1a26bbf2-1192-4139-b6fb-cb7fc1c826ce_extraction.json',
 '2d035c4b-cdfa-4982-87dc-916fe07a0824_545d42f0-5eb0-4eec-987e-49386f952502_extraction.json']

In [12]:
def clean_filename(filename):
    return filename[:-17] if "translation.json" in filename else filename[:-16]

print(clean_filename('2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-526e-4736-8e5b-bc95ae00f890_translation.json'))
print(clean_filename('2d035c4b-cdfa-4982-87dc-916fe07a0824_249f1d30-1a50-42de-a3a6-20c295f770c7_extraction.json'))

2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-526e-4736-8e5b-bc95ae00f890
2d035c4b-cdfa-4982-87dc-916fe07a0824_249f1d30-1a50-42de-a3a6-20c295f770c7

In [13]:
df_X_sample["filename_cleaned"] = df_X_sample["fichier"].apply(clean_filename)
df_y["filename_cleaned"] = df_y["fichier"].apply(clean_filename)

In [14]:
df_X_sample["filename_cleaned"].head().to_list()

['2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-526e-4736-8e5b-bc95ae00f890',
 'a5050600-95ef-43d8-a5fa-a57c791bf843_6bdcc550-786f-466f-adf8-b3788f458e11',
 'a5050600-95ef-43d8-a5fa-a57c791bf843_0b17a3f7-07fd-420f-a7e9-c6ac3a91f0d8',
 'a5050600-95ef-43d8-a5fa-a57c791bf843_6e530b73-6a24-47b2-956c-ea6cae802254',
 'c619f0e1-7c22-4047-adb2-df4dec6643ba_3694c83a-bd98-a9b0-b01a-f5e6ee3de1ac']

In [15]:
df_y["filename_cleaned"].head().to_list()

['2d035c4b-cdfa-4982-87dc-916fe07a0824_249f1d30-1a50-42de-a3a6-20c295f770c7',
 '2d035c4b-cdfa-4982-87dc-916fe07a0824_019a0add-5b4a-4cb9-b999-daeb5e2a54fd',
 '55d674cc-3389-4cf6-ab7c-1f1b9fa1b6ed_02a55241-ccf4-4f9a-87ac-23e0ac71e576',
 '9f980dcf-b431-4e67-876f-2b8e288b7900_1a26bbf2-1192-4139-b6fb-cb7fc1c826ce',
 '2d035c4b-cdfa-4982-87dc-916fe07a0824_545d42f0-5eb0-4eec-987e-49386f952502']

In [17]:
# merge
df = df_X_sample.merge(df_y, how="left", on="filename_cleaned")

columns_to_keep = [
    "filename_cleaned",
    "date_words",
    "date_words_len",
    "CareBeginDate_day_format01",
    "CareBeginDate_day_format02",
    "CareBeginDate_day_format03",
    "CareBeginDate_month_format01",
    "CareBeginDate_month_format02",
    "CareBeginDate_month_format03",
    "CareBeginDate_year_format01",
    "CareBeginDate_year_format02",
    "CareBeginDate_hour_format01",
    "CareBeginDate_hour_format02",
    "CareBeginDate_hour_format03",
    "CareBeginDate_hour_format04",
    "CareBeginDate_hour_format05",
    "CareBeginDate_hour_format06"
]
df = df[columns_to_keep]
df.head()

,filename_cleaned,date_words,date_words_len,CareBeginDate_day_format01,CareBeginDate_day_format02,CareBeginDate_day_format03,CareBeginDate_month_format01,CareBeginDate_month_format02,CareBeginDate_month_format03,CareBeginDate_year_format01,CareBeginDate_year_format02,CareBeginDate_hour_format01,CareBeginDate_hour_format02,CareBeginDate_hour_format03,CareBeginDate_hour_format04,CareBeginDate_hour_format05,CareBeginDate_hour_format06
0,2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-...,"[20 4012 1022 à, à 11h]",2,lundi,24,24,janvier,01,1,22,2022,11h00,11h,11,11h00,11h,11
1,a5050600-95ef-43d8-a5fa-a57c791bf843_6bdcc550-...,[],0,jeudi,31,31,mars,03,3,22,2022,14h00,14h,14,2h00,2h,2
2,a5050600-95ef-43d8-a5fa-a57c791bf843_0b17a3f7-...,[],0,jeudi,31,31,mars,03,3,22,2022,12h00,12h,12,12h00,12h,12
3,a5050600-95ef-43d8-a5fa-a57c791bf843_6e530b73-...,[],0,jeudi,03,3,février,02,2,22,2022,8h25,8h,8,8h25,8h,8
4,c619f0e1-7c22-4047-adb2-df4dec6643ba_3694c83a-...,[],0,samedi,27,27,novembre,11,11,21,2021,23h00,23h,23,11h00,11h,11

In [25]:
# evaluation : we check if each "CareBeginDate_..." is in one of the dates found in "date_words"

In [37]:
df.head(20)

,filename_cleaned,date_words,date_words_len,CareBeginDate_day_format01,CareBeginDate_day_format02,CareBeginDate_day_format03,CareBeginDate_month_format01,CareBeginDate_month_format02,CareBeginDate_month_format03,CareBeginDate_year_format01,CareBeginDate_year_format02,CareBeginDate_hour_format01,CareBeginDate_hour_format02,CareBeginDate_hour_format03,CareBeginDate_hour_format04,CareBeginDate_hour_format05,CareBeginDate_hour_format06
0,2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-...,"[20 4012 1022 à, à 11h]",2,lundi,24,24,janvier,01,1,22,2022,11h00,11h,11,11h00,11h,11
1,a5050600-95ef-43d8-a5fa-a57c791bf843_6bdcc550-...,[],0,jeudi,31,31,mars,03,3,22,2022,14h00,14h,14,2h00,2h,2
2,a5050600-95ef-43d8-a5fa-a57c791bf843_0b17a3f7-...,[],0,jeudi,31,31,mars,03,3,22,2022,12h00,12h,12,12h00,12h,12
3,a5050600-95ef-43d8-a5fa-a57c791bf843_6e530b73-...,[],0,jeudi,03,3,février,02,2,22,2022,8h25,8h,8,8h25,8h,8
4,c619f0e1-7c22-4047-adb2-df4dec6643ba_3694c83a-...,[],0,samedi,27,27,novembre,11,11,21,2021,23h00,23h,23,11h00,11h,11
5,a5050600-95ef-43d8-a5fa-a57c791bf843_2a711fc5-...,[6 mois],1,vendredi,01,1,avril,04,4,22,2022,20h00,20h,20,8h00,8h,8
6,f0caa21b-c11d-40a3-98ec-e2df3d2b9cc4_7a1dc5f5-...,[le 28 septembre à 8h],1,samedi,20,20,juin,06,6,20,2020,6h30,6h,6,6h30,6h,6
7,9f980dcf-b431-4e67-876f-2b8e288b7900_00e71591-...,[],0,jeudi,02,2,décembre,12,12,21,2021,8h00,8h,8,8h00,8h,8
8,9d42ce6f-8537-49a9-a121-c8ae1dc7cda8_5264fbdd-...,[le 29 décembre à 13h45],1,mardi,29,29,décembre,12,12,20,2020,13h45,13h,13,1h45,1h,1
9,55d674cc-3389-4cf6-ab7c-1f1b9fa1b6ed_84cf1f24-...,[],0,vendredi,18,18,mars,03,3,22,2022,8h00,8h,8,8h00,8h,8
10,c619f0e1-7c22-4047-adb2-df4dec6643ba_141bd639-...,[le jeudi 16 décembre 2000],1,jeudi,16,16,décembre,12,12,21,2021,8h00,8h,8,8h00,8h,8
11,74b154c1-e265-4cb9-8e71-0c9bbc3dc880_3ca3d9f0-...,"[le 22 décembre, à 7h15]",2,mercredi,22,22,décembre,12,12,21,2021,7h15,7h,7,7h15,7h,7
12,9f980dcf-b431-4e67-876f-2b8e288b7900_819bc8a5-...,[le 29 mars à],1,mardi,29,29,mars,03,3,22,2022,8h00,8h,8,8h00,8h,8
13,2d035c4b-cdfa-4982-87dc-916fe07a0824_8fbc2732-...,"[6052, 1021, à 6h15]",2,jeudi,06,6,mai,05,5,21,2021,6h15,6h,6,6h15,6h,6
14,2d035c4b-cdfa-4982-87dc-916fe07a0824_59d59006-...,"[le 7 décembre, 8h]",1,lundi,07,7,décembre,12,12,20,2020,8h00,8h,8,8h00,8h,8
15,9f980dcf-b431-4e67-876f-2b8e288b7900_7b53d92e-...,[le 15 mars],1,mardi,15,15,mars,03,3,22,2022,8h00,8h,8,8h00,8h,8
16,9d42ce6f-8537-49a9-a121-c8ae1dc7cda8_9b13a582-...,[le 16 novembre à 10h20],1,lundi,16,16,novembre,11,11,20,2020,10h20,10h,10,10h20,10h,10
17,74b154c1-e265-4cb9-8e71-0c9bbc3dc880_1ddfb130-...,"[le 16 avril, à 8h, le 20 août et, le 27 août]",4,vendredi,20,20,août,08,8,21,2021,8h00,8h,8,8h00,8h,8
18,55d674cc-3389-4cf6-ab7c-1f1b9fa1b6ed_456f8b9e-...,[le 30 juillet 2021],1,vendredi,30,30,juillet,07,7,21,2021,9h00,9h,9,9h00,9h,9
19,f0caa21b-c11d-40a3-98ec-e2df3d2b9cc4_8a82a0c8-...,[6 mois],1,mercredi,12,12,août,08,8,20,2020,11h00,11h,11,11h00,11h,11

In [74]:
df_score = df[["filename_cleaned", "date_words"]].copy()

df_score["score_day_format01"] = df.apply(lambda x: x["CareBeginDate_day_format01"] in " ".join(x["date_words"]), axis=1)
df_score["score_day_format02"] = df.apply(lambda x: x["CareBeginDate_day_format02"] in " ".join(x["date_words"]), axis=1)
df_score["score_day_format03"] = df.apply(lambda x: x["CareBeginDate_day_format03"] in " ".join(x["date_words"]), axis=1)
df_score["score_month_format01"] = df.apply(lambda x: x["CareBeginDate_month_format01"] in " ".join(x["date_words"]), axis=1)
df_score["score_month_format02"] = df.apply(lambda x: x["CareBeginDate_month_format02"] in " ".join(x["date_words"]), axis=1)
df_score["score_month_format03"] = df.apply(lambda x: x["CareBeginDate_month_format03"] in " ".join(x["date_words"]), axis=1)
df_score["score_year_format01"] = df.apply(lambda x: x["CareBeginDate_year_format01"] in " ".join(x["date_words"]), axis=1)
df_score["score_year_format02"] = df.apply(lambda x: x["CareBeginDate_year_format02"] in " ".join(x["date_words"]), axis=1)
df_score["score_hour_format01"] = df.apply(lambda x: x["CareBeginDate_hour_format01"] in " ".join(x["date_words"]), axis=1)
df_score["score_hour_format02"] = df.apply(lambda x: x["CareBeginDate_hour_format02"] in " ".join(x["date_words"]), axis=1)
df_score["score_hour_format03"] = df.apply(lambda x: x["CareBeginDate_hour_format03"] in " ".join(x["date_words"]), axis=1)
df_score["score_hour_format04"] = df.apply(lambda x: x["CareBeginDate_hour_format04"] in " ".join(x["date_words"]), axis=1)
df_score["score_hour_format05"] = df.apply(lambda x: x["CareBeginDate_hour_format05"] in " ".join(x["date_words"]), axis=1)
df_score["score_hour_format06"] = df.apply(lambda x: x["CareBeginDate_hour_format06"] in " ".join(x["date_words"]), axis=1)

df_score["score_day"] = \
    df_score["score_day_format01"] | \
    df_score["score_day_format02"] | \
    df_score["score_day_format03"]

df_score["score_month"] = \
    df_score["score_month_format01"] | \
    df_score["score_month_format02"] | \
    df_score["score_month_format03"]

df_score["score_month"] = \
    df_score["score_month_format01"] | \
    df_score["score_month_format02"] | \
    df_score["score_month_format03"]

df_score["score_year"] = \
    df_score["score_year_format01"] | \
    df_score["score_year_format02"]

df_score["score_hour"] = \
    df_score["score_hour_format01"] | \
    df_score["score_hour_format02"] | \
    df_score["score_hour_format03"] | \
    df_score["score_hour_format04"] | \
    df_score["score_hour_format05"] | \
    df_score["score_hour_format06"]

df_score.head()

,filename_cleaned,date_words,score_day_format01,score_day_format02,score_day_format03,score_month_format01,score_month_format02,score_month_format03,score_year_format01,score_year_format02,score_hour_format01,score_hour_format02,score_hour_format03,score_hour_format04,score_hour_format05,score_hour_format06,score_day,score_month,score_year,score_hour
0,2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-...,"[20 4012 1022 à, à 11h]",False,False,False,False,True,True,True,False,False,True,True,False,True,True,False,True,True,True
1,a5050600-95ef-43d8-a5fa-a57c791bf843_6bdcc550-...,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,a5050600-95ef-43d8-a5fa-a57c791bf843_0b17a3f7-...,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,a5050600-95ef-43d8-a5fa-a57c791bf843_6e530b73-...,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,c619f0e1-7c22-4047-adb2-df4dec6643ba_3694c83a-...,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [75]:
df_score["score"] = (df_score["score_day"].astype(int) + df_score["score_month"].astype(int) + \
                     df_score["score_year"].astype(int) + df_score["score_hour"].astype(int) ) / 4

df_score.head()

,filename_cleaned,date_words,score_day_format01,score_day_format02,score_day_format03,score_month_format01,score_month_format02,score_month_format03,score_year_format01,score_year_format02,...,score_hour_format02,score_hour_format03,score_hour_format04,score_hour_format05,score_hour_format06,score_day,score_month,score_year,score_hour,score
0,2d035c4b-cdfa-4982-87dc-916fe07a0824_1275c4e7-...,"[20 4012 1022 à, à 11h]",False,False,False,False,True,True,True,False,...,True,True,False,True,True,False,True,True,True,0.75
1,a5050600-95ef-43d8-a5fa-a57c791bf843_6bdcc550-...,[],False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.00
2,a5050600-95ef-43d8-a5fa-a57c791bf843_0b17a3f7-...,[],False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.00
3,a5050600-95ef-43d8-a5fa-a57c791bf843_6e530b73-...,[],False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.00
4,c619f0e1-7c22-4047-adb2-df4dec6643ba_3694c83a-...,[],False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.00

In [76]:
df_score[["date_words", "score_day", "score_month", "score_year", "score_hour", "score"]].head(20)

,date_words,score_day,score_month,score_year,score_hour,score
0,"[20 4012 1022 à, à 11h]",False,True,True,True,0.75
1,[],False,False,False,False,0.00
2,[],False,False,False,False,0.00
3,[],False,False,False,False,0.00
4,[],False,False,False,False,0.00
5,[6 mois],False,False,False,False,0.00
6,[le 28 septembre à 8h],False,False,False,False,0.00
7,[],False,False,False,False,0.00
8,[le 29 décembre à 13h45],True,True,False,True,0.75
9,[],False,False,False,False,0.00
10,[le jeudi 16 décembre 2000],True,True,False,False,0.50
11,"[le 22 décembre, à 7h15]",True,True,False,True,0.75
12,[le 29 mars à],True,True,False,False,0.50
13,"[6052, 1021, à 6h15]",True,True,True,True,1.00
14,"[le 7 décembre, 8h]",True,True,False,True,0.75
15,[le 15 mars],True,True,False,False,0.50
16,[le 16 novembre à 10h20],True,True,True,True,1.00
17,"[le 16 avril, à 8h, le 20 août et, le 27 août]",True,True,False,True,0.75
18,[le 30 juillet 2021],True,True,True,False,0.75
19,[6 mois],False,False,False,False,0.00